apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_DB: sagardb
  POSTGRES_USER: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA== # base64 for 'postgrespassword'
