apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/sagardb

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  API_KEY: c2VjcmV0YXBpa2V5
